# Data Preprocessing Tools

## Importing the libraries

In [2]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 

## Importing the dataset

In [3]:
dataset = pd.read_csv('Data.csv')
# colon means range, we are going to exclude last column; we are gathering first 3 columns
X = dataset.iloc[:, :-1].values 
# to get last column we do not need to specify a range 
Y = dataset.iloc[:, -1].values

In [ ]:
print(X)

In [ ]:
print(Y)

## Taking care of missing data

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') # Create an object of the SimpleImputer class 
imputer.fit(X[:, 1:3]) # Look for missing values in age/salary column
# The transofmr function is going to do the actual column manipulations
X[:, 1:3] = imputer.transform(X[:, 1:3]) # Replace the columns with our changes 

In [9]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X)) # Need to format around np array so we get the format that we need for the ML models we are going to develop 



In [12]:
print(X) # With our new changes, the 3 countries (France/Spain/Germany) are in 3 columns seperated by numerical order (1s/0s)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [14]:
# We now want to encode the Yes/No into 0s and 1s
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder() # no arguments 
y = le.fit_transform(Y) # do not need to make it into a np array

In [16]:
print(y) # No --> 0, and Yes --> 1

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [18]:
print(X_train) # 8 customers taken randomly from the data set

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [19]:
print(X_test) # 2 customers taken randomly from data set into test set

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [21]:
print(y_train) # 8 outputs for the remainder excluding training set 

[0 1 0 0 1 1 0 1]


In [22]:
print(y_test) # 2 outputs corresponding to the 2 random values 

[0 1]


## Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:]) # Takes index of 3 to the end; 3 and 4
X_test[:, 3:] = sc.fit_transform(X_test[:, 3:])

In [24]:
print(X_train) # Now the variables are on the same scale: -/+ 2

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [25]:
print(X_test) # Age and Salary scaled to take values by  -/+ 2

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]
